### ISSUE TITLE
timeClient issue

### ISSUE THREAD

**Issue by Lacybad** [sorriso93/IOTroutertraffic#1]
IOTroutertraffic:65: error: 'timeClient' was not declared in this scope

   if (timeClient.update())

How could i fix this issue?

**Comment by sorriso93** [comment]
Hi maybe you're using different library version. Please note NTPCLIENTLIB should be 2.5.1 and NTPCLIENT lib 3.1.0.
Let me know

**Comment by Lacybad** [comment]
Hello!

Thank you for the responce. You were right, my NTPCLIENTLIB was a bit out of date.I made a very beginners mistake. After updating to latest version no errors from Arduino  IDE :)

**Comment by sorriso93** [comment]
good!

**Comment by udrojunior** [comment]
Hello, I'm having the same error, I've already updated the NPTCLIENT to the most current version and I'm still encountering this error, could you help me?

**Comment by sorriso93** [comment]
It's strange because yesterday I compiled with last version of board (esp8266) and libraries with no issues (ntpclient 3.2.1, ntpclientlib 3.0.2 beta)
